#lang sicp

(define (element-of-set? x set)
  (cond ((null? set) #f)
        ((> x (car set)) #f)
        ((= x (car set)) #t)
        (else (element-of-set? x (cdr set)))))

(define (intersection-set set1 set2)
  (if (or (null? set1) (null? set2))
      '()
      (let ((x1 (car set1))
            (x2 (car set2)))
        (cond ((= x1 x2)
               (cons x1 (intersection-set (cdr set1)
                                          (cdr set2))))
              ((< x1 x2)
               (intersection-set (cdr set1) set2))
              ((< x2 x1)
               (intersection-set set1 (cdr set2)))))))

(define (adjoin-set x set)
  (cond ((null? set) (list x))
        ((> x (car set))
         (cons (car set) (adjoin-set x (cdr set))))
        ((< x (car set)) (cons x set))
        (else set)))

(define x0 '())
(define x1 (adjoin-set 3 x0))
(define x2 (adjoin-set -2 x1))
(define x3 (adjoin-set 0 x2))
(define x4 (adjoin-set 7 x3))
(display x0)
(newline)
(display x1)
(newline)
(display x2)
(newline)
(display x3)
(newline)
(display x4)
(newline)
