(define (fib n)
  (fib-iter 1 0 0 1 n))

(define (fib-iter a b p q count)
  (cond ((= count 0) b)
        ((even? count)
         (let ((q-sq (* q q))
               (p-sq (* p p))
               (pq (* p q)))
           (fib-iter a
                     b
                     (+ q-sq p-sq)
                     (+ q-sq (* 2 pq))
                     (/ count 2))))
        (else (fib-iter (+ (* b q) (* a q) (* a p))
                        (+ (* b p) (* a q))
                        p
                        q
                        (- count 1)))))

(define (recursive-fib n)
  (cond ((= n 0) 0)
        ((= n 1) 1)
        (else (+ (recursive-fib (- n 1)) (recursive-fib (- n 2))))))
      

(display "Low fibbonacci numbers by recursive method:")
(newline)
(recursive-fib 0)
(recursive-fib 1)
(recursive-fib 2)
(recursive-fib 3)
(recursive-fib 4)
(recursive-fib 5)
(recursive-fib 6)
(recursive-fib 7)
(recursive-fib 8)
(recursive-fib 9)
(recursive-fib 10)
(display "Low fibonacci number by iterative method with logarithmic growth:")
(newline)
(fib 0)
(fib 1)
(fib 2)
(fib 3)
(fib 4)
(fib 5)
(fib 6)
(fib 7)
(fib 8)
(fib 9)
(fib 10)
(display "Fibbonacci number 10'000 by recursive method:")
(newline)
(fib 10000)
(display "Medium fibonacci numbers by iterative method with logarithmic growth:")
(newline)
(display "35: ")
(recursive-fib 35)
(display "40: ")
(recursive-fib 40)
(display "45: ")
(recursive-fib 45)
(display "50: ")
(recursive-fib 50)