(define (repeated f n)
  (if (= n 1)
      f
      (lambda (x) (f ((repeated f (- n 1)) x)))))

(define (square x) (* x x))
(define (cube x) (* x x x))

(define (exp2 a n)
  (if (= n 0)
      1
      (* a (exp2 a (- n 1)))))

(define tolerance 0.00001)
(define (average a b) (/ (+ a b) 2))

(define (average-damp f)
  (lambda (x) (average x (f x))))

(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (let ((next (f guess)))
      (if (close-enough? guess next)
          next
          (try next))))
  (try first-guess))

(define (sqrt-alt x)
  (fixed-point ((repeated average-damp 1) (lambda (y) (/ x y)))
               1.0))

(sqrt-alt 9)

(define (log2 x)
  (/ (log x) (log 2)))

(define (cube-root x)
  (fixed-point ((repeated average-damp 1) (lambda (y) (/ x (square y))))
               1.0))

(cube-root 27)

(define (fourth-root x)
  (fixed-point ((repeated average-damp 2) (lambda (y) (/ x (cube y))))
               1.0))

(fourth-root 16)

(define (nth-root x n damping-factor)
  (fixed-point ((repeated average-damp damping-factor) (lambda (y) (/ x (exp2 y (- n 1))))) 1.0))

(display "Checking nth-roots:")
(newline)
(display "2:")
(newline)
(nth-root (exp2 3 2) 2 1)
(display "3:")
(newline)
(nth-root (exp2 3 3) 3 1)
(display "4:")
(newline)
(nth-root (exp2 3 4) 4 2)
(display "5:")
(newline)
(nth-root (exp2 3 5) 5 2)
(display "6:")
(newline)
(nth-root (exp2 3 6) 6 2)
(display "7:")
(newline)
(nth-root (exp2 3 7) 7 2)
(display "8:")
(newline)
(nth-root (exp2 3 8) 8 3)
(display "9:")
(newline)
(nth-root (exp2 3 9) 9 3)
(display "10:")
(newline)
(nth-root (exp2 3 10) 10 3)
(display "11:")
(newline)
(nth-root (exp2 3 11) 11 3)
(display "12:")
(newline)
(nth-root (exp2 3 12) 12 3)
(display "13:")
(newline)
(nth-root (exp2 3 13) 13 3)
(display "14:")
(newline)
(nth-root (exp2 3 14) 14 3)
(display "15:")
(newline)
(nth-root (exp2 3 15) 15 3)
(display "16:")
(newline)
(nth-root (exp2 3 16) 16 4)

(define (calculate-required-damping-factor n)
  (floor (log2 n)))

(define (nth-root-damped x n)
  (fixed-point
   (
    (repeated average-damp(calculate-required-damping-factor n))
    (lambda (y) (/ x (exp2 y (- n 1)))))
   1.0))

(let ((n 2)) (nth-root-damped (exp2 3 n) n))
(let ((n 3)) (nth-root-damped (exp2 3 n) n))
(let ((n 4)) (nth-root-damped (exp2 3 n) n))
(let ((n 5)) (nth-root-damped (exp2 3 n) n))
(let ((n 6)) (nth-root-damped (exp2 3 n) n))
(let ((n 7)) (nth-root-damped (exp2 3 n) n))
(let ((n 287)) (nth-root-damped (exp2 3 n) n))